import { AppLanguage } from './types';

export const translations = {
  ru: {
    // Sidebar
    allTasks: "Все задачи",
    projects: "Проекты",
    planned: "Запланировано",
    waiting: "Ожидает",
    pending: "Ожидает",
    inWork: "В работе",
    in_progress: "В работе",
    testing: "Тестирование",
    completed: "Выполнено",
    cancelled: "Отменено",
    tags: "Теги",
    releases: "Релизы",
    roadmap: "Roadmap",
    settings: "Настройки",
    notes: "Заметки",
    dashboard: "Дашборд",
    search: "Поиск",

    // Task Priorities
    priorityNone: "Без приоритета",
    priorityLow: "Низкий",
    priorityMedium: "Средний",
    priorityHigh: "Высокий",
    priorityUrgent: "Срочный",

    // Task Types
    typeBug: "Баг",
    typeBugDesc: "Описание и отслеживание программных ошибок",
    typeFeature: "Фича",
    typeFeatureDesc: "Новая функциональность или улучшение",
    typeRelease: "Релиз",
    typeReleaseDesc: "Планирование и отслеживание выпуска",
    typeRefactor: "Рефакторинг",
    typeRefactorDesc: "Улучшение архитектуры и качества кода",
    typeDocumentation: "Документация",
    typeDocumentationDesc: "Спецификации, руководства и знания",
    typePrompt: "AI Промпт",
    typePromptDesc: "Полезный промпт для нейросетей (Gemini, ChatGPT)",

    // Task workflow statuses descriptions
    statusPlannedDesc: "Задача запланирована на будущее",
    statusWaitingDesc: "Ожидает начала действий/разблокировки",
    statusInWorkDesc: "В данный момент находится в разработке",
    statusTestingDesc: "Этап тестирования и верификации",
    statusCompletedDesc: "Успешно завершена и проверена",
    statusCancelledDesc: "Отменена или больше не актуальна",

    // Sidebar items and General
    newProject: "Новый проект",
    newRelease: "Новый релиз",
    newTask: "Новая задача",
    addProject: "Добавить проект",
    addRelease: "Добавить релиз",
    addNote: "Новая заметка",
    searchPlaceholder: "Глобальный поиск по заголовкам, коду, промптам...",
    filterBy: "Фильтровать по",
    filterProject: "Все проекты",
    filterPriority: "Все приоритеты",
    filterTag: "Все теги",
    noTasksFound: "Задачи не найдены. Создайте новую задачу или измените фильтры.",
    noProjectsFound: "Проекты отсутствуют. Создайте проект для группировки задач.",
    noNotesFound: "Завалявшихся мыслей нет. Напишите временную заметку!",
    taskCount: "задач",
    taskSingle: "задача",
    taskPlural: "задачи",

    // Dashboard
    totalTasks: "Всего задач",
    activeTasks: "В работе",
    completedTasksCount: "Выполнено",
    upcomingReleases: "Ближайшие релизы",
    recentActivity: "Последние изменения",
    progressTrend: "Динамика прогресса",
    distributionByStatus: "Задачи по статусам",
    distributionByProject: "Задачи по проектам",
    generalStats: "Метрики производительности",
    recentActivityEmpty: "История активности пуста. Начните работу над задачами!",

    // Task Form and details
    taskTitle: "Заголовок задачи",
    taskTitlePlaceholder: "Например: Интеграция Stripe платежей",
    taskDescription: "Описание (Markdown)",
    taskDescriptionPlaceholder: "Напишите детальное описание или техническую спецификацию задачи...",
    chooseType: "Выберите тип задачи",
    chooseStatus: "Выберите рабочий статус",
    selectProject: "Проект",
    selectPriority: "Приоритет",
    saveTask: "Сохранить задачу",
    createTaskBtn: "Создать задачу",
    editTask: "Редактировать задачу",
    deleteTask: "Удалить задачу",
    cancel: "Отмена",
    backToList: "Назад к списку",
    tagsPlaceholder: "Введите тег и нажмите Enter",
    checklistTitle: "Чек-лист прогресса",
    addChecklistItem: "Добавить пункт...",
    attachmentsTitle: "Вложения / Скриншоты",
    dragDropText: "Перетащите файлы сюда или нажмите для выбора",
    fileNotFoundError: "Файл не найден. Возможно, он был удалён или перемещён.",
    codeSnippetsTitle: "Фрагменты кода",
    addCodeSnippet: "Добавить код",
    codeTitlePlaceholder: "Название файла/функции (например: auth.ts)",
    codeContentPlaceholder: "Вставьте ваш исходный код здесь...",
    promptsTitle: "Промпты для AI моделей",
    addPromptBtn: "Добавить промпт",
    promptTitlePlaceholder: "Например: Оптимизация SQL-запроса",
    promptContentPlaceholder: "Напишите текст промпта...",
    historyTitle: "История изменений задачи",

    // Roadmap
    roadmapTitle: "Дорожная карта релизов",
    roadmapDesc: "Управление версиями проекта и запланированными фичами.",
    releaseName: "Название релиза",
    releaseVersion: "Версия",
    releaseDate: "Дата выпуска",
    releaseChanges: "Список изменений (через Enter)",
    releaseProgress: "Прогресс релиза",
    plannedFeatures: "Запланировано для этой версии",
    emptyRoadmap: "Нет запланированных релизов.",

    // Notes
    notesTitle: "Быстрые заметки разработчика",
    notesPlaceholder: "Напишите ваши идеи, структуры API или временные мысли...",
    noteSaved: "Заметка сохранена",
    noteTitlePlaceholder: "Заголовок заметки",

    // Settings
    settingsTitle: "Настройки Flux Tasks",
    themeSectionTitle: "Тема и оформление интерфейса",
    themeSectionDesc: "Настройка визуального стиля, цветовых палитр, степени размытия стекла и фонового рисунка рабочего стола.",
    systemSectionTitle: "Системные настройки и База Данных",
    systemSectionDesc: "Выбор языка приложения, резервное копирование SQLite-базы, импорт/экспорт и сброс настроек.",
    languageLabel: "Язык интерфейса",
    accentColorLabel: "Акцентный цвет приложения",
    glassTintLabel: "Оттенок стеклянного материала",
    glassPresetLabel: "Степень матовости стекла (Материал)",
    bgStyleLabel: "Стиль заднего фона desktop",
    tintNeutral: "Нейтральный (Платина)",
    tintBlue: "Арктический синий",
    tintPurple: "Неоновый фиолетовый",
    tintEmerald: "Изумрудный зеленый",
    tintAmber: "Янтарный оранжевый",
    presetCrystal: "Кристальный (Кристально прозрачный)",
    presetFrosted: "Матовый (Мягкое размытие)",
    presetAcrylic: "Акрил (Темный глубокий)",
    presetUltraBlur: "Экстра матовый (Сильное размытие)",
    presetMinimal: "Минималистичный (Экономичный)",
    bgOrbit: "Орбитальный космос (Плавный градиент)",
    bgAurora: "Северное сияние",
    bgDeepNoir: "Глубокий нуар (Темный матовый)",
    bgCrystalLake: "Горное озеро",

    // SQL local DB simulator
    dbSection: "Локальная База Данных SQLite",
    dbLocation: "Файл базы данных",
    dbEngineStatus: "Статус SQLite Engine",
    dbEngineLive: "РАБОТАЕТ (Локальный песочный файл)",
    dbLocationPath: "%APPDATA%/Flux Tasks/tasks.db",
    dbBackupsTitle: "Резервные копии (Backups)",
    createBackup: "Создать копию вручную",
    restoreBackup: "Восстановить из JSON",
    exportData: "Экспортировать проект",
    backupSuccess: "Резервная копия успешно создана в папке backups/",
    restoreSuccess: "Данные успешно восстановлены!",
    exportSuccess: "Экспортировано успешно в формате",
    dbTotalRecords: "Количество записей в DB",
    autoBackupLabel: "Автоматическое резервное копирование",
    everyDay: "Ежедневно",
    everyWeek: "Еженедельно",
    disabled: "Отключено",

    // Misc
    unassigned: "Холостой проект",
    minutesAgo: "мин. назад",
    hoursAgo: "ч. назад",
    justNow: "Только что",
    aiGenerateTitle: "Написать ИИ (Gemini)",
    aiGenerateDesc: "Сгенерировать ТЗ по заголовку",
    copyCode: "Копировать",
    copied: "Скопировано!",
    kanbanDesc: "Управляйте рабочим статусом напрямую через выпадающее меню • По 2 карточки в ряд",
    searchFiltersHelp: "Попробуйте изменить поисковой запрос или фильтры на верхней панели",
    dbRecordsInSqlite: "записей в SQLite",
    inDevelopment: "в разработке",
    closureRate: "процент завершения",
    sprintCompletion: "Выполнение спринта",
    doneLabel: "Готово",
    changesLabel: "изменений",
    filesSimulatedText: "Поддерживаются изображения, PDF, TXT или ZIP файлы",
    taskProperties: "Свойства задачи",
    workflowStage: "Этап работы",
    projectAssociation: "Связанный проект",
    priorityLevel: "Уровень приоритета",
    developerNotes: "Заметки разработчика",
    developerNotesPlaceholder: "Мысли разработчика, временные указания, эндпоинты системы...",
    markAsPlanned: "Запланировать",
    markAsCompleted: "Выпустить",
    deleteLabel: "Удалить",
    releasedOn: "Выпущено",
    updatedLabel: "Обновлено",
    inThisList: "в этом списке",
    workspaceDescPlaceholder: "Описание проекта, совместное рабочее пространство...",
    controlDesignSystemDesc: "Управление параметрами дизайна, макетом и файлами базы данных SQLite.",
    customColorHex: "Свой hex цвет:",
    localSandboxStorage: "Локальное хранилище песочницы",
    simulatedDbSize: "Размер базы данных:",
    recordCounters: "Счетчики записей:",
    exportMarkdownSpec: "Экспорт в Markdown Спецификацию",
    resetDatabaseToDefaults: "Сбросить БД по умолчанию",
    backupTransaction: "Резервная копия: сохранено записей",
    autoLabel: "АВТО",
    manualLabel: "РУЧНОЙ",
    scratchMode: "Временный черновик Flux",
    untitledScratchpad: "Безымянная заметка",
    noNoteActive: "Нет активной заметки",
    selectOrCreateNoteDesc: "Нажмите «Новая заметка» выше или выберите её из списка слева.",
    addNoteBtn: "Добавить заметку",
    namePlaceholder: "Название...",
    okLabel: "ОК",
    taskSpecDetails: "Детали спецификации задачи",
    premiumTaskCreator: "Профессиональное создание задач",
    tasksWorkspace: "Рабочая область задач",
    activeStyleStartsFrom: "Текущий градиент сгенерирован из",
    convergesGradientInto: "и плавно сходится в",
    bulkExportWorkspaceDocs: "Пакетный экспорт документов рабочей области"
  },
  uk: {
    // Sidebar
    allTasks: "Усі завдання",
    projects: "Проєкти",
    planned: "Заплановано",
    waiting: "Очікує",
    pending: "Очікує",
    inWork: "В роботі",
    in_progress: "В роботі",
    testing: "Тестування",
    completed: "Виконано",
    cancelled: "Скасовано",
    tags: "Теги",
    releases: "Релізи",
    roadmap: "Roadmap",
    settings: "Налаштування",
    notes: "Нотатки",
    dashboard: "Дашборд",
    search: "Пошук",

    // Task Priorities
    priorityNone: "Без пріоритету",
    priorityLow: "Низький",
    priorityMedium: "Середній",
    priorityHigh: "Високий",
    priorityUrgent: "Терміновий",

    // Task Types
    typeBug: "Баг",
    typeBugDesc: "Звіт та відстеження програмних помилок",
    typeFeature: "Фіча",
    typeFeatureDesc: "Нова функціональність або покращення",
    typeRelease: "Реліз",
    typeReleaseDesc: "Планування та відстеження релізу",
    typeRefactor: "Рефакторинг",
    typeRefactorDesc: "Покращення архітектури та якості коду",
    typeDocumentation: "Документація",
    typeDocumentationDesc: "Специфікації, інструкції та знання",
    typePrompt: "AI Промпт",
    typePromptDesc: "Корисний промпт для нейромереж (Gemini, Claude)",

    // Task workflow statuses descriptions
    statusPlannedDesc: "Завдання заплановано на майбутнє",
    statusWaitingDesc: "Очікує початку дій або розблокування",
    statusInWorkDesc: "В даний момент знаходиться в розробці",
    statusTestingDesc: "Етап тестування та верифікації",
    statusCompletedDesc: "Успішно завершено та перевірено",
    statusCancelledDesc: "Скасовано або втратило актуальність",

    // Sidebar items and General
    newProject: "Новий проєкт",
    newRelease: "Новий реліз",
    newTask: "Нове завдання",
    addProject: "Додати проєкт",
    addRelease: "Додати реліз",
    addNote: "Нова нотатка",
    searchPlaceholder: "Глобальний пошук за заголовками, кодом, промптами...",
    filterBy: "Фільтрувати за",
    filterProject: "Усі проєкти",
    filterPriority: "Усі пріоритети",
    filterTag: "Усі теги",
    noTasksFound: "Завдання не знайдено. Створіть завдання або змініть фільтри.",
    noProjectsFound: "Проєкти відсутні. Створіть проєкт для групування завдань.",
    noNotesFound: "Немає нотаток. Створіть швидку ідею!",
    taskCount: "завдань",
    taskSingle: "завдання",
    taskPlural: "завдання",

    // Dashboard
    totalTasks: "Всього завдань",
    activeTasks: "В роботі",
    completedTasksCount: "Виконано",
    upcomingReleases: "Найближчі релізи",
    recentActivity: "Останні зміни",
    progressTrend: "Динаміка прогресу",
    distributionByStatus: "Завдання за статусами",
    distributionByProject: "Завдання за проєктами",
    generalStats: "Метрики продуктивності",
    recentActivityEmpty: "Історія активності порожня. Почніть роботу над завданнями!",

    // Task Form and details
    taskTitle: "Заголовок завдання",
    taskTitlePlaceholder: "Наприклад: Інтеграція платежів Stripe",
    taskDescription: "Опис (Markdown)",
    taskDescriptionPlaceholder: "Напишіть детальний опис або специфікацію завдання...",
    chooseType: "Виберіть тип завдання",
    chooseStatus: "Виберіть робочий статус",
    selectProject: "Проєкт",
    selectPriority: "Пріоритет",
    saveTask: "Зберегти завдання",
    createTaskBtn: "Створити завдання",
    editTask: "Редагувати",
    deleteTask: "Видалити",
    cancel: "Скасувати",
    backToList: "Назад до списку",
    tagsPlaceholder: "Введіть тег та натисніть Enter",
    checklistTitle: "Чек-лист прогресу",
    addChecklistItem: "Додати пункт...",
    attachmentsTitle: "Вкладення / Скріншоти",
    dragDropText: "Перетягніть файли сюди або натисніть для вибору",
    fileNotFoundError: "Файл не знайдено. Можливо, його було видалено або переміщено.",
    codeSnippetsTitle: "Фрагменти коду",
    addCodeSnippet: "Додати код",
    codeTitlePlaceholder: "Назва файлу (наприклад: core.py)",
    codeContentPlaceholder: "Вставте ваш вихідний код тут...",
    promptsTitle: "Промпти для штучного інтелекту",
    addPromptBtn: "Добавить промпт",
    promptTitlePlaceholder: "Наприклад: Оптимізація бази даних",
    promptContentPlaceholder: "Напишіть текст вашого запиту...",
    historyTitle: "Історія змін завдання",

    // Roadmap
    roadmapTitle: "Дорожня карта релізів",
    roadmapDesc: "Керування версіями проєкту та запланованими фічами.",
    releaseName: "Назва релізу",
    releaseVersion: "Версія",
    releaseDate: "Дата випуску",
    releaseChanges: "Список змін (через Enter)",
    releaseProgress: "Прогрес релізу",
    plannedFeatures: "Заплановано для версії",
    emptyRoadmap: "Немає запланованих релізів.",

    // Notes
    notesTitle: "Швидкі нотатки розробника",
    notesPlaceholder: "Запишіть ваші ідеї, структури API або тимчасові речі...",
    noteSaved: "Нотатка збережена",
    noteTitlePlaceholder: "Заголовок нотатки",

    // Settings
    settingsTitle: "Налаштування Flux Tasks",
    themeSectionTitle: "Тема та оформлення інтерфейсу",
    themeSectionDesc: "Налаштування візуального стилю, колірних палітр, ступеня розмиття скла та фонового малюнка робочого столу.",
    systemSectionTitle: "Системні налаштування та База Даних",
    systemSectionDesc: "Вибір мови програми, резервне копіювання бази SQLite, імпорт/експорт та скидання налаштувань.",
    languageLabel: "Мова інтерфейсу",
    accentColorLabel: "Акцентний колір застосунку",
    glassTintLabel: "Відтінок скла",
    glassPresetLabel: "Оформлення скла (Матеріал)",
    bgStyleLabel: "Тематичний фон робочого столу",
    tintNeutral: "Нейтральний (Платина)",
    tintBlue: "Арктичний синій",
    tintPurple: "Неоновий фіолетовий",
    tintEmerald: "Смарагдовий зелений",
    tintAmber: "Бурштиновий помаранчевий",
    presetCrystal: "Кристал (Прозорий)",
    presetFrosted: "Матовий (М'яке розмиття)",
    presetAcrylic: "Акрил (Глибокий матовий)",
    presetUltraBlur: "Екстра матовий (Максимальне розмиття)",
    presetMinimal: "Мінімалістичний",
    bgOrbit: "Орбітальний космос",
    bgAurora: "Північне сяйво",
    bgDeepNoir: "Глибокий нуар",
    bgCrystalLake: "Гірське озеро",

    // SQL local DB simulator
    dbSection: "Локальна База Даних SQLite",
    dbLocation: "Файл бази даних",
    dbEngineStatus: "Статус SQLite Engine",
    dbEngineLive: "АКТИВНИЙ (Локальний файл-пісочниця)",
    dbLocationPath: "%APPDATA%/Flux Tasks/tasks.db",
    dbBackupsTitle: "Резервні копії",
    createBackup: "Створити копію",
    restoreBackup: "Відновити з JSON",
    exportData: "Експортувати проєкт",
    backupSuccess: "Резервну копію згенеровано в папці backups/",
    restoreSuccess: "Дані успішно відновлено!",
    exportSuccess: "Проєкт експортовано у форматі",
    dbTotalRecords: "Кількість записів в DB",
    autoBackupLabel: "Автоматичне копіювання",
    everyDay: "Щодня",
    everyWeek: "Щотижня",
    disabled: "Вимкнено",

    // Misc
    unassigned: "Холостий проєкт",
    minutesAgo: "хв. тому",
    hoursAgo: "год. тому",
    justNow: "Щойно",
    aiGenerateTitle: "Написати ШІ (Gemini)",
    aiGenerateDesc: "Згенерувати ТЗ за заголовком",
    copyCode: "Копіювати",
    copied: "Скопійовано!",
    kanbanDesc: "Керуйте робочим статусом напряму через випадаюче меню • По 2 картки в ряд",
    searchFiltersHelp: "Спробуйте змінити пошуковий запит або фільтри на верхній панелі",
    dbRecordsInSqlite: "записів у SQLite",
    inDevelopment: "в розробці",
    closureRate: "відсоток завершення",
    sprintCompletion: "Виконання спринту",
    doneLabel: "Готово",
    changesLabel: "змін",
    filesSimulatedText: "Підтримуються зображення, PDF, TXT або ZIP файли",
    taskProperties: "Властивості завдання",
    workflowStage: "Етап роботи",
    projectAssociation: "Пов'язаний проєкт",
    priorityLevel: "Рівень пріоритету",
    developerNotes: "Нотатки розробника",
    developerNotesPlaceholder: "Думки розробника, тимчасові вказівки, ендпоінти системи...",
    markAsPlanned: "Запланувати",
    markAsCompleted: "Випустити",
    deleteLabel: "Вилучити",
    releasedOn: "Випущено",
    updatedLabel: "Оновлено",
    inThisList: "в цьому списку",
    workspaceDescPlaceholder: "Опис проєкту, спільний робочий простір...",
    controlDesignSystemDesc: "Керування параметрами дизайну, макетом та файлами бази даних SQLite.",
    customColorHex: "Свій hex колір:",
    localSandboxStorage: "Локальне сховище пісочниці",
    simulatedDbSize: "Розмір бази даних:",
    recordCounters: "Лічильники записів:",
    exportMarkdownSpec: "Експорт в Markdown Специфікацію",
    resetDatabaseToDefaults: "Скинути БД за замовчуванням",
    backupTransaction: "Резервна копія: збережено записів",
    autoLabel: "АВТО",
    manualLabel: "РУЧНИЙ",
    scratchMode: "Тимчасова чернетка Flux",
    untitledScratchpad: "Нотатка без назви",
    noNoteActive: "Немає активної нотатки",
    selectOrCreateNoteDesc: "Натисніть «Нова нотатка» вище або виберіть її зі списку ліворуч.",
    addNoteBtn: "Додати нотатку",
    namePlaceholder: "Назва...",
    okLabel: "ОК",
    taskSpecDetails: "Деталі специфікації завдання",
    premiumTaskCreator: "Професійне створення завдань",
    tasksWorkspace: "Робоча область завдань",
    activeStyleStartsFrom: "Поточний градієнт згенерований з",
    convergesGradientInto: "і плавно замикається у",
    bulkExportWorkspaceDocs: "Пакетний експерт документів робочої області"
  },
  en: {
    // Sidebar
    allTasks: "All Tasks",
    projects: "Projects",
    planned: "Planned",
    waiting: "Waiting",
    pending: "Waiting",
    inWork: "In Progress",
    in_progress: "In Progress",
    testing: "Testing",
    completed: "Completed",
    cancelled: "Cancelled",
    tags: "Tags",
    releases: "Releases",
    roadmap: "Roadmap",
    settings: "Settings",
    notes: "Notes",
    dashboard: "Dashboard",
    search: "Search",

    // Task Priorities
    priorityNone: "No Priority",
    priorityLow: "Low",
    priorityMedium: "Medium",
    priorityHigh: "High",
    priorityUrgent: "Urgent",

    // Task Types
    typeBug: "Bug",
    typeBugDesc: "Report and track software bugs or defects",
    typeFeature: "Feature",
    typeFeatureDesc: "New functionality or product improvement",
    typeRelease: "Release",
    typeReleaseDesc: "Release deployment and launch planning",
    typeRefactor: "Refactor",
    typeRefactorDesc: "Improve architecture and clean core script",
    typeDocumentation: "Documentation",
    typeDocumentationDesc: "Technical specs, user manuals and wikis",
    typePrompt: "AI Prompt",
    typePromptDesc: "Store high-performance instructions for AI models",

    // Task workflow statuses descriptions
    statusPlannedDesc: "Task is planned for upcoming milestones",
    statusWaitingDesc: "Waiting for action, approval or unblocking",
    statusInWorkDesc: "Actively in development or under active duty",
    statusTestingDesc: "In the testing, review or verification phase",
    statusCompletedDesc: "Successfully resolved, built and merged",
    statusCancelledDesc: "Aborted, archived or duplicate",

    // Sidebar items and General
    newProject: "New Project",
    newRelease: "New Release",
    newTask: "New Task",
    addProject: "Add Project",
    addRelease: "Add Release",
    addNote: "New Note",
    searchPlaceholder: "Global search across title, specs, code, prompts...",
    filterBy: "Filter by",
    filterProject: "All Projects",
    filterPriority: "All Priorities",
    filterTag: "All Tags",
    noTasksFound: "No tasks found matching current filters. Create one!",
    noProjectsFound: "No projects created yet. Form a project to map your work.",
    noNotesFound: "Scratchpad is empty. Sketch a transient idea right away!",
    taskCount: "tasks",
    taskSingle: "task",
    taskPlural: "tasks",

    // Dashboard
    totalTasks: "Total Tasks",
    activeTasks: "Active Tasks",
    completedTasksCount: "Completed",
    upcomingReleases: "Upcoming Releases",
    recentActivity: "Recent Activity",
    progressTrend: "Progress Curve",
    distributionByStatus: "Tasks by Status",
    distributionByProject: "Tasks by Project",
    generalStats: "Performance Metrics",
    recentActivityEmpty: "No activity history found. Kick off your workspace duties!",

    // Task Form and details
    taskTitle: "Task Title",
    taskTitlePlaceholder: "e.g., Integrate Stripe Payment Webhooks",
    taskDescription: "Description (Markdown Supported)",
    taskDescriptionPlaceholder: "A thorough description, user stories or spec details...",
    chooseType: "Select Task Type",
    chooseStatus: "Select Workflow Status",
    selectProject: "Project Linkage",
    selectPriority: "Priority Tier",
    saveTask: "Save Task",
    createTaskBtn: "Create Task",
    editTask: "Edit Task",
    deleteTask: "Delete Task",
    cancel: "Cancel",
    backToList: "Back to List",
    tagsPlaceholder: "Enter tag and press Enter",
    checklistTitle: "Progress Checklist",
    addChecklistItem: "Add new checklist node...",
    attachmentsTitle: "Attachments / Screenshot files",
    dragDropText: "Drag files here or click to browse",
    fileNotFoundError: "File not found. It might have been deleted or moved.",
    codeSnippetsTitle: "Associated Code Snippets",
    addCodeSnippet: "Add Code Block",
    codeTitlePlaceholder: "Filename or identifier (e.g. server.js)",
    codeContentPlaceholder: "Paste your code snippet here...",
    promptsTitle: "AI Prompt Presets",
    addPromptBtn: "Add Prompt Block",
    promptTitlePlaceholder: "e.g., Rewrite into optimized async loops",
    promptContentPlaceholder: "Write the developer prompt body...",
    historyTitle: "Task Activity Changelog",

    // Roadmap
    roadmapTitle: "Release Roadmap Roadmap",
    roadmapDesc: "Govern the version life cycles, timelines & completed items.",
    releaseName: "Release Title",
    releaseVersion: "Target Version",
    releaseDate: "Target Date",
    releaseChanges: "Changelog inputs (press Enter to separate)",
    releaseProgress: "Release Progress",
    plannedFeatures: "Features set for this Version",
    emptyRoadmap: "Zero active releases in view.",

    // Notes
    notesTitle: "Developer Scratchpad Logs",
    notesPlaceholder: "Scribble code architecture drafts, local snippets or quick tags...",
    noteSaved: "Scratchpad synchronized",
    noteTitlePlaceholder: "Scratchpad Title",

    // Settings
    settingsTitle: "Flux Tasks Settings",
    themeSectionTitle: "Interface Theme & Styling",
    themeSectionDesc: "Customize your visual design style, accent color gradients, glass blur transparency level, and desktop wallpaper backgrounds.",
    systemSectionTitle: "System Controls & Database Utilities",
    systemSectionDesc: "Select interface language, manage local SQLite sandboxed backups, compile workspace documents, or reset database.",
    languageLabel: "Application Language",
    accentColorLabel: "Vibrancy Accent Color",
    glassTintLabel: "Liquid Glass Tinting Aura",
    glassPresetLabel: "Glass Frost material density",
    bgStyleLabel: "Desktop Interactive Background Canvas",
    tintNeutral: "Platinum Neutral",
    tintBlue: "Arctic Aqua",
    tintPurple: "Glow Violet",
    tintEmerald: "Flux Jade",
    tintAmber: "Amber Sun",
    presetCrystal: "Crystal (High Light transmission)",
    presetFrosted: "Frosted (Balanced blur & depth)",
    presetAcrylic: "Acrylic (Subtle night theme)",
    presetUltraBlur: "Ultra Blur (Dreamlike diffusion)",
    presetMinimal: "Minimalist Clear",
    bgOrbit: "Orbital Nebula (Slow fluid motion)",
    bgAurora: "Aurora Borealis",
    bgDeepNoir: "Deep Noir Dark room",
    bgCrystalLake: "Summit Mountain Lake",

    // SQL local DB simulator
    dbSection: "Local SQLite DB Settings",
    dbLocation: "Local SQLite Database File",
    dbEngineStatus: "Sqlite3 Driver Runtime Engine",
    dbEngineLive: "ONLINE (Local browser sandbox filesystem)",
    dbLocationPath: "%APPDATA%/Flux Tasks/tasks.db",
    dbBackupsTitle: "Backup & Restore Utilities",
    createBackup: "Capture Instant Database Backup",
    restoreBackup: "Restore database from Backup file",
    exportData: "Bulk Client Export Project Data",
    backupSuccess: "Backup snapshots captured successfully into backups/",
    restoreSuccess: "Database file restored and state refreshed successfully!",
    exportSuccess: "Successfully compiled and exported",
    dbTotalRecords: "Total Simulated Database Records",
    autoBackupLabel: "Automated cron scheduling tasks",
    everyDay: "Run Daily",
    everyWeek: "Run Weekly",
    disabled: "Disabled",

    // Misc
    unassigned: "General Workspace",
    minutesAgo: "m ago",
    hoursAgo: "h ago",
    justNow: "Just now",
    aiGenerateTitle: "Write with AI (Gemini Option)",
    aiGenerateDesc: "Draft full specifications from title",
    copyCode: "Copy",
    copied: "Copied!",
    kanbanDesc: "Manage status directly via dropdown menu • 2 cards per row Grid",
    searchFiltersHelp: "Try adjusting search queries or top filter presets in the header block",
    dbRecordsInSqlite: "records in SQLite",
    inDevelopment: "in development",
    closureRate: "closure rate",
    sprintCompletion: "Sprint Completion",
    doneLabel: "Done",
    changesLabel: "changes",
    filesSimulatedText: "Image, PDF, TXT or ZIP files simulated",
    taskProperties: "Task Properties",
    workflowStage: "Workflow Stage",
    projectAssociation: "Project Association",
    priorityLevel: "Priority Level",
    developerNotes: "Developer Notes",
    developerNotesPlaceholder: "Developer mental notes, temporary pointers, system endpoints...",
    markAsPlanned: "Mark as Planned",
    markAsCompleted: "Mark as Completed",
    deleteLabel: "Delete",
    releasedOn: "Released",
    updatedLabel: "Updated",
    inThisList: "in this list",
    workspaceDescPlaceholder: "Project description, collaborative workspace...",
    controlDesignSystemDesc: "Control design system attributes, layout parameters, and SQLite simulator files.",
    customColorHex: "Custom color hex:",
    localSandboxStorage: "Local sandbox storage",
    simulatedDbSize: "Simulated database sizes:",
    recordCounters: "Record counters:",
    exportMarkdownSpec: "Export to Markdown Specification",
    resetDatabaseToDefaults: "Reset database to Defaults",
    backupTransaction: "Backup transaction: saved records",
    autoLabel: "AUTO",
    manualLabel: "MANUAL",
    scratchMode: "Flux Scratch Mode",
    untitledScratchpad: "Untitled scratchpad",
    noNoteActive: "No note active",
    selectOrCreateNoteDesc: "Click New Note above or select one from drawer list.",
    addNoteBtn: "Add note",
    namePlaceholder: "Name...",
    okLabel: "Ok",
    taskSpecDetails: "Task Specification Details",
    premiumTaskCreator: "Premium Task Creator Pipeline",
    tasksWorkspace: "Tasks Workspace",
    activeStyleStartsFrom: "Currently active style starts from",
    convergesGradientInto: "and converges gradient into",
    bulkExportWorkspaceDocs: "Export Entire Workspace Documents"
  }
};

export type TranslationKey = keyof typeof translations.ru;

export function getTranslation(lang: AppLanguage, key: TranslationKey): string {
  const dict = translations[lang] || translations.ru;
  return dict[key] || translations.ru[key] || String(key);
}
